shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('cloth/<int:pk>', views.cloth_detail, name='cloth_detail'),
]

street_style/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include(('shop.urls', 'street_style'), namespace='shop')),
    path('users/', include(('users.urls', 'street_style'), namespace='users')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_out/', views.sign_out, name='sign_out'),
]

shop/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'shop_categories'


class Brand(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'shop_brands'


color = [
    ('Черный', 'Черный'),
    ('Белый', 'Белый'),
    ('Синий', 'Синий'),
    ('Коричневый', 'Коричневый'),
    ('Зеленый', 'Зеленый'),
    ('Красный', 'Красный'),
    ('Желтый', 'Желтый'),
    ('Розвый', 'Розвый'),
    ('Фиолетовый', 'Фиолетовый'),
    ('Оранжевый', 'Оранжевый'),
]


# size = (
#     ('X', 'X'),
#     ('S', 'S'),
#     ('M', 'M'),
#     ('L', 'L'),
#     ('XL', 'XL'),
#     ('XXL', 'XXL'),
#     ('XXXL', 'XXXL'),
#     ('XXXXL', 'XXXXL'),
# )


class Cloth(models.Model):
    title = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    size = models.IntegerField(null=True)
    size2 = models.CharField(max_length=255, choices=(
        ('X', 'X'),
        ('S', 'S'),
        ('M', 'M'),
        ('L', 'L'),
        ('XL', 'XL'),
        ('XXL', 'XXL'),
        ('XXXL', 'XXXL'),
        ('XXXXL', 'XXXXL'),
    ), null=True, blank=True)
    color = models.CharField(max_length=255, choices=color, null=True)
    image = models.ImageField(blank=True, null=True,)
    available = models.BooleanField(default=True)
    gender = models.CharField(max_length=255, choices=(
        ('Man', 'Man'),
        ('Woman', 'Woman'),
        ('Unisex', 'Unisex'),
    ), null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'shop_clothes'


class Slide(models.Model):
    image = models.ImageField(default='slide.jpg')


RATE_CHOICES = [
    (1, '1 - Trash'),
    (2, '2 - Bad'),
    (3, '3 - Ok'),
    (4, '4 - Good'),
    (5, '5 - Perfect')
]


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Cloth, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    text = models.TextField(blank=True)
    rate = models.PositiveSmallIntegerField(choices=RATE_CHOICES, null=True)

    def __str__(self):
        return self.user.username


class Image(models.Model):
    product = models.ForeignKey(Cloth, on_delete=models.CASCADE, related_name='cloth')
    image1 = models.ImageField(null=True)
    image2 = models.ImageField(null=True)
    image3 = models.ImageField(null=True)
    image4 = models.ImageField(blank=True)

    def str(self):
        return str(self.product)

users/models.py
from django.db import models

shop/forms.py
from django import forms

from shop.models import RATE_CHOICES, Review


class RateForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea(attrs={'class': 'textarea'}), label='Write review text')
    rate = forms.ChoiceField(choices=RATE_CHOICES, required=True, label='Rate product from 1 to 5')

    class Meta:
        model = Review
        fields = ['text', 'rate']

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'Create any username'}))
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'input', 'placeholder': 'Create any password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input', 'placeholder': 'Repeat password'}))

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class SignInForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'Write username'}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'input', 'placeholder': 'Write password'}))

    class Meta:
        model = User
        fields = ['username', 'password']

shop/views.py
from django.db.models import Q
from django.shortcuts import render

from .forms import RateForm
from .models import Cloth, Slide, Review, Image


# Create your views here.
def home(request):
    cloth = Cloth.objects.all()
    category = request.GET.get('category')
    brand = request.GET.get('brand')
    slides = Slide.objects.all()
    cloth = cloth.filter(category=category) if category else cloth
    cloth = cloth.filter(brand=brand) if brand else cloth
    search = request.GET.get('search')
    cloth = cloth.filter(
        Q(title__icontains=search) | Q(price__icontains=search)) if search else cloth

    return render(request, 'home.html', {'cloth': cloth, 'slides': slides})


def cloth_detail(request, pk):
    product = Cloth.objects.get(pk=pk)
    form = RateForm(request.POST or None)
    images = Image.objects.filter(product=product)
    reviews = Review.objects.filter(product=product)
    if request.method == "POST" and form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.product = product
        instance.save()
    return render(request, 'cloth_detail.html', {'product': product, 'form': form, 'reviews': reviews,'images':images})

users/views.py
from django.contrib.auth import login, logout
from django.shortcuts import redirect, render
from . import forms


def sign_up(request):
    form = forms.SignUpForm(request.POST)
    if form.is_valid() and request.method == 'POST':
        form.save()
        return redirect('users:sign_in')
    form = forms.SignUpForm()
    return render(request, 'sign_up.html', {'form': form})


def sign_in(request):
    form = forms.SignInForm(data=request.POST)
    if form.is_valid() and request.method == 'POST':
        user = form.get_user()
        login(request, user)
        return redirect('shop:home')
    form = forms.SignInForm()
    return render(request, 'index.html', {'form': form})


def sign_out(request):
    logout(request)
    return redirect('users:sign_in')

shop/templates/about.html
{% extends 'base_layout.html' %}
{% block content %}

{% endblock %}

shop/templates/base_layout.html
<!doctype html>
{% load brand %}
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} Street Style {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'bulma.css' %}">
    <link rel="stylesheet" href="{% static 'bulma.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-carousel@4.0.3/dist/css/bulma-carousel.min.css">
</head>
<body>
<style>
    body {
        background: url(" {% static 'images/fon5.jpg' %} ");
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-position: center;
        background-size: cover;
    }

    nav {
        box-shadow: 1px 5px 5px deeppink;
    }
</style>
<nav class="navbar has-background-black is-fixed-top " role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'shop:home' %}">
            <img src="{% static 'images/images.png' %}" width="100" height="50">
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item has-text-success-dark">
                Главная
            </a>


            <div class="navbar-item has-dropdown is-hoverable has-text-primary-dark">
                <a class="navbar-link has-text-success-dark">
                    Бренды
                </a>

                {% brands %}


            </div>
        </div>

        <div class="navbar-end">
            <form action="{% url 'shop:home' %}" method="get" class="mb-4">
                <div class="field has-addons mt-4 mr-2 ">
                    <div class="control">
                        <input class="input is-rounded pl-6" type="search" placeholder="Поиск по названию и цене"
                               name="search">
                    </div>
                    <div class="control">
                        <button class="button is-rounded is-warning" type="submit">
                            Search
                        </button>
                    </div>
                </div>
            </form>
            <div class="navbar-item">
                <div class="buttons">
                    {% if user.is_authenticated %}
                    <button class="button is-primary" aria-haspopup="true" aria-controls="dropdown-menu">
                        Добро пожаловать <span class="has-text-weight-bold mx-1">{{ user }}</span>
                    </button>
                    {% else %}
                    <a href="{% url 'users:sign_up' %}" class="button is-danger">
                        <strong>Зарегистрироваться</strong>
                    </a>
                    <a href="{% url 'users:sign_in' %}" class="button is-light">
                        Авторизоваться
                    </a>

                    {% endif %}
                </div>

            </div>
            {% if user.is_authenticated %}
            <span class="navbar-item">
   <div class="dropdown is-hoverable">
       <div class="dropdown-trigger has-background-danger-light">
           <button class="button is-info " aria-haspopup="true" aria-controls="dropdown-menu">
               Мой профиль
           </button>
       </div>
       <div class="dropdown-menu" id="dropdown-menu" role="menu">
           <div class="dropdown-content">
               <a href="" class="dropdown-item has-text-primary ">
                  Редактировать профиль
               </a>
               <a href="" class="dropdown-item has-text-warning-dark">
                   Сброс пароля
               </a>
               <hr class="dropdown-divider">
               <a href="{% url 'users:sign_out' %}" class="dropdown-item has-text-danger">
                   выход
               </a>
           </div>
       </div>
   </div>
</span>
            {% endif %}

        </div>
    </div>
</nav>
{% block slide %}
{% endblock %}
{% block content %}
{% endblock %}
<footer class="footer cvet1">
    <div class="container is-small">
        <div class="">

            <br>


            <div class="columns">
                <div class="column is-3">

                    <div class="footer__menu">
                        <a href="" class="title is-5  has-text-white">Покупателям</span></a>

                    </div>
                    <br>
                    <p class="subtitle has-text-weight-medium  is-7">
                        <a href="" class="has-text-white">Способ оплаты</a><br><br>
                        <a href="" class="has-text-white">Доставка</a><br><br>
                        <a href="" class="has-text-white">Возврат товара</a><br><br>
                        <a href="" class="has-text-white">Возврат денежных средств</a><br><br>
                        <a href="" class="has-text-white">Правила продажи</a>
                        <a href="" class="has-text-white">Публичная оферта</a>
                    </p>
                </div>
                <br>
                <div class="column is-3">
                    <div class="footer__menu ">
                        <a href="" class="title is-5  has-text-white">Партнерам</a>

                    </div>
                    <p class="subtitle has-text-weight-medium pt-5 is-7">
                        <a href="" class="has-text-white">Покупайте в Street_Style</a><br><br>
                        <a href="" class="has-text-white">Пункт выдачи</a><br><br>
                    </p>
                </div>
                <br>
                <div class="column is-3">
                    <div class="footer__menu ">
                        <a href="" class="title is-5  has-text-white">Компания</a>

                    </div>
                    <p class="subtitle has-text-weight-medium pt-5 is-7">
                        <a href="" class="has-text-white">О нас</a><br><br>
                        <a href="" class="has-text-white">Реквизиты</a><br><br>
                        <a href="" class="has-text-white">Пресс цетр</a><br><br>
                        <a href="" class="has-text-white">Контыкты</a>
                    </p>
                </div>
                <div class="column is-3">
                    <div class="footer__menu">
                        <a href="" class="title is-5  has-text-white">Мы в соцсетяx</a>

                    </div>
                    <p class="subtitle has-text-weight-medium pt-5 is-7">
                        <a href="https://www.instagram.com/_z_m_080903/" class="has-text-white">Istagram</a><br><br>
                        <a href="" class="has-text-white">VK</a><br><br>
                        <a href="https://t.me/Pandasecurity_0809" class="has-text-white">Telegram</a><br><br>
                        <a href="" class="has-text-white">Facebook</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="columns is-centered ">
        <div class="column is-half">
            <div class="has-text-centered">

                <p class="title has-text-white is-6  mt-4 mb-5">© Все права защищены
                    Политика конфиденциальности
                    Публичная оферта</p>
            </div>
        </div>
    </div>

</footer>
<script src="https://cdn.jsdelivr.net/npm/bulma-carousel@4.0.3/dist/js/bulma-carousel.min.js"></script>
<script>
    bulmaCarousel.attach('#carousel-demo', {
        slidesToScroll: 1,
        slidesToShow: 1,
        infinite: true,
    });
</script>


</body>
</html>

shop/templates/brands.html
<div class="navbar-dropdown">
    {% for brand in brands %}
    <a class="navbar-item" href="{% url 'shop:home' %}?brand={{ brand.pk }}">
        {{ brand }}
    </a>
    {% endfor %}
</div>

shop/templates/category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

shop/templates/cloth_detail.html
{% extends 'base_layout.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'bulma.css' %}">
    <link rel="stylesheet" href="{% static 'script.js' %}">
    <title>Title</title>
</head>
<body>
{% block content %}
    <div class="cvet" style="margin-top: 100px">


        <div class="box">
            <h1 class="title has-text-centered">{{ product.title }}</h1>
            <div class="" style="color: black;font-size: 25px;font-weight: bold;margin-left: 45px">{{ product.name }}</div>
            <br>
            <br>
            <div class="columns" style="margin-left: -110px">
                {% for image in images %}
                    <div id="pSlider" class="mt-3" style="width: 300px">
                        <ol id="slider-container" dir="ltr">
                            <a href="reklama.html">
                                <li class="li_slide">
                                    <img class="fotki" id="photo1" src="{{ image.image1.url }}"
                                                                width="450px" height="80px"
                                        alt="">
                                    <div class="slide-snapper"></div>
                                    <a class="prev_slide" href="#slide_4"></a> <a class="next_slide"
                                                                                  href="#slide_2"></a></li>
                            </a>
                            <li class="li_slide">
                                <img class="fotki" id="photo1" src="{{ image.image2.url }}"
                                     width="450px" height="80px"
                                     alt="">
                                <div class="slide-snapper"></div>
                                <a class="prev_slide" href="#slide_1"></a> <a class="next_slide" href="#slide_3"></a>
                            </li>
                            <li id="slide_3" class="li_slide">
                                <img class="fotki" id="photo1" src="{{ image.image3.url }}"
                                                                width="450px" height="80px"
                                        alt="">
                                <div class="slide-snapper"></div>
                                <a class="prev_slide" href="#slide_2"></a> <a class="next_slide" href="#slide_4"></a>
                            </li>
                            <li id="slide_4" class="li_slide">
                                <img class="fotki" id="photo1" src="{{ image.image4.url }}"
                                                                width="450px" height="80px"
                                        alt="">
                                <div class="slide-snapper"></div>
                                <a class="prev_slide" href="#slide_3"></a> <a class="next_slide" href="#slide_1"></a>
                            </li>
                        </ol>
                    </div>
                {% endfor %}
                <div class="column is-4">
                    <div class="" style="color: black;font-size: 25px;font-weight: bold">О товаре</div>
                    <div class="mt-3" style="color: black;font-weight: bold;font-size: 15px">Дополнитльная информация
                    </div>
                    <div class="mt-1 has-text-grey" style="font-size: 14px">Бренд
                        ----------------------------------- {{ product.brand }}</div>
                    <div class="mt-1 has-text-grey" style="font-size: 14px">Размер
                        ----------------------------------- {{ product.size }}
                    </div>
                    <div class="mt-1 has-text-grey" style="font-size: 14px">Цвет
                        ----------------------------------- {{ product.color }}
                    </div>
                    <div class="mt-1 has-text-grey" style="font-size: 14px">Пол
                        ----------------------------------- {{ product.gender }}
                    </div>
                    <div class="mt-1 has-text-grey" style="font-size: 14px">Произведено
                        ----------------------------------- {{ product.created }}</div>
                    <div class="mt-4" style="font-weight: bold;color: black">Описание</div>
                    <div class="mt-1 has-text-grey" style="font-size: 14px">{{ product.description }}</div>
                </div>
                <div class="column is-3 ml-6">
                    <div class="box mt-2 has-background-info">
                        <span style="color: black;font-weight: bold;font-size: 15px">от</span><span
                            style="color: black;font-weight: bold;font-size: 30px;margin-left: 10px">{{ product.price }} сум</span>
                        {% if user.is_authenticated %}
                            {% if user.profile %}
                                <div class="box mt-2"
                                     style="background: rgb(86, 128, 233);display: flex;justify-content: center;color: white;border-radius: 10px;font-weight: bold">
                                    <a href="{% url 'shop:home' %}?product={{ product.pk }}" class="order"
                                       style="color: white">Добавить
                                        в корзину</a></div>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
            <br>
        </div>
    </div>
{% endblock %}
</body>
</html>

shop/templates/home.html
{% extends 'base_layout.html' %}
{% block slide %}

<section class="section">
<div class="container-slide mb-6 mt-6">
   <div id="carousel-demo" class="carousel">
       {% for slide in slides %}
           <div class="item-1">
               <img class="slider-img" src="{{ slide.image.url }}" alt="">
           </div>
       {% endfor %}
   </div>
</div>
</section>

{% endblock %}

{% block content %}

    <div class="box has-background-black">
        <h1 class="title has-text-centered is-1 has-text-white">
      Добро пожаловать в мир кросовок
    </h1>
    </div>

<style>


    .card {
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        overflow: hidden;
        width: 400px;
    }

    .card img {
        width: 100%;
        height: 250px;
        object-fit: cover;
    }

    .card-content {
        padding: 20px;
    }

    .card-title {
        font-size: 24px;
        font-weight: bold;
        margin-bottom: 10px;
    }

    .card-description {
        font-size: 16px;
        color: #666;
        margin-bottom: 20px;
    }

    .card-details {
        font-size: 14px;
        color: #888;
        margin-bottom: 10px;
    }

    .card-price {
        font-size: 22px;
        color: #f39c12;
    }
</style>
<div class="columns  is-centered is-multiline">
    {% for i in cloth %}
    <a class="column  mt-6  is-3 m-4 " style="border-radius: 30px" href="{% url 'shop:cloth_detail' i.pk %}">
        <div class="card b1">
            <img src="{{ i.image.url }}" alt="Машина">
            <div class="card-content">
                <div class="card-title"> {{ i.title }}</div>

                <div class="card-details">
                    <p>Дата :{{ i.date }}</p>
                    <p>Размер :{{i.size}}</p>

                    <p>Категория : {{ i.category }}</p>

                    <p>Бренд:{{ i.brand }}</p>
                </div>
                <div class="card-price">Цена: {{ i.price }} сум</div>
            </div>
        </div>
    </a>
    {% endfor %}
</div>

{% endblock %}

users/templates/index.html
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>LogIn Form</title>
    <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Hind:300' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>


    <link rel="stylesheet" href="{% static  'sign_in.css'%}">
    <link rel="stylesheet" href="{% static 'bulma.css' %}">

</head>

<body>
<div id="login-button">
    <img src="https://cdn-icons-png.flaticon.com/512/1785/1785340.png">
    </img>
</div>
<div id="container">

    <span class="close-btn">
    <img src="https://cdn4.iconfinder.com/data/icons/miu/22/circle_close_delete_-128.png"></img>
  </span>

    <!--  <form>-->
    <!--    {% csrf_token %}-->
    <!--    {% for field in form %}-->

    <!--            {{ field }}-->
    <!--        {% endfor %}-->
    <!--    <button type="submit" class="button is-success is-fullwidth">Войти</button>-->
    <!--    <div id="remember-container">-->


    <!--      <span id="forgotten">Forgotten password</span>-->
    <!--    </div>-->
    <!--</form>-->
    <form class=" has-text-centered p-5" method="post">

        <p class="title">Sign in</p>
        {% csrf_token %}
        {% for field in form %}

        <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
        {{ field }}
        {% endfor %}

        <div class="has-text-centered my-2">
            <button type="submit" class="button is-success is-fullwidth">Войти</button>
        </div>
        <hr class="has-background-grey-lighter">
        <a href="{% url 'users:sign_up' %}">Страница регистрации</a>
    </form>
</div>

<!-- Forgotten Password Container -->

<script src='http://cdnjs.cloudflare.com/ajax/libs/gsap/1.16.1/TweenMax.min.js'></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

<script src="{% static 'index.js' %}"></script>

</body>
</html>

users/templates/sign_in.html
{% extends "base_layout.html" %}

{% block content %}
<div class="columns is-centered mt-6 mb-6">
    <div class="column is-5">
        <form class="site-form has-background-light has-text-centered" method="post">
            <p class="title">Sign in</p>
            {% csrf_token %}
            {% for field in form %}
            <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
            {{ field }}
            {% endfor %}

            <div class="has-text-centered my-2">
                <button type="submit" class="button is-success is-fullwidth">Войти</button>
            </div>
            <hr class="has-background-grey-lighter">
            <div class="is-size-5 has-text-grey-light">У вас нет аккаунта?</div>
            <a href="{% url 'users:sign_up' %}" class="button is-ghost">
                Move to register page
            </a>
        </form>
    </div>
</div>
{% endblock %}

users/templates/sign_up.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>LogIn Form</title>
    <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Hind:300' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>


    <link rel="stylesheet" href="{% static  'sign_in.css'%}">
    <link rel="stylesheet" href="{% static 'bulma.css' %}">

</head>

<body>
<div id="login-button" >
    <img src="https://cdn-icons-png.flaticon.com/512/1785/1785340.png">
    </img>
</div>
<div id="container">

    <span class="close-btn">
    <img src="https://cdn4.iconfinder.com/data/icons/miu/22/circle_close_delete_-128.png"></img>
  </span>

    <!--  <form>-->
    <!--    {% csrf_token %}-->
    <!--    {% for field in form %}-->

    <!--            {{ field }}-->
    <!--        {% endfor %}-->
    <!--    <button type="submit" class="button is-success is-fullwidth">Войти</button>-->
    <!--    <div id="remember-container">-->


    <!--      <span id="forgotten">Forgotten password</span>-->
    <!--    </div>-->
    <!--</form>-->
    <form class="site-form  has-text-centered p-5" method="post">
        <p class="title">Sign up</p>
        {% csrf_token %}
        {% for field in form %}
        <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
        {{ field }}
        {% endfor %}
        <div class="has-text-centered my-2">
            <button type="submit" class="button is-success is-fullwidth">Зарегистрироваться</button>
        </div>
        <hr class="has-background-grey-lighter">

        <a href="{% url 'users:sign_in' %}" class=" ">
            Перейти на страницу входа
        </a>
    </form>
</div>

<!-- Forgotten Password Container -->

<script src='http://cdnjs.cloudflare.com/ajax/libs/gsap/1.16.1/TweenMax.min.js'></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

<script src="{% static 'index.js' %}"></script>

</body>
</html>